const $=s=>document.querySelector(s), mealsEl=$('#meals'); let photoData='';
let state=JSON.parse(localStorage.getItem('meallog-state')||'{"goal":1800,"meals":[]}');
function save(){localStorage.setItem('meallog-state',JSON.stringify(state));render()}
function localISO(d=new Date()){let z=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${z(d.getMonth()+1)}-${z(d.getDate())}T${z(d.getHours())}:${z(d.getMinutes())}`}
function todayKey(){return localISO().slice(0,10)}
function render(){let today=state.meals.filter(m=>m.time.slice(0,10)===todayKey()).sort((a,b)=>a.time.localeCompare(b.time));let sum=k=>today.flatMap(m=>m.foods).reduce((a,f)=>a+(+f[k]||0),0);let cal=Math.round(sum('calories'));$('#totalCal').textContent=cal;$('#remainCal').textContent=Math.max(0,state.goal-cal);$('#carbs').textContent=Math.round(sum('carbs'));$('#protein').textContent=Math.round(sum('protein'));$('#fat').textContent=Math.round(sum('fat'));$('#todayLabel').textContent=new Intl.DateTimeFormat('ko-KR',{month:'long',day:'numeric',weekday:'long'}).format(new Date());mealsEl.innerHTML=today.length?'':'<div class="empty">아직 기록한 음식이 없어요.<br>아래 버튼으로 첫 식사를 기록해보세요.</div>';today.forEach(m=>{let c=m.foods.reduce((a,f)=>a+(+f.calories||0),0), names=m.foods.map(f=>f.name).join(', ');let el=document.createElement('article');el.className='meal';el.innerHTML=`${m.photo?`<img src="${m.photo}">`:'<div>🍽️</div>'}<div><h3>${m.type} · ${new Date(m.time).toLocaleTimeString('ko-KR',{hour:'2-digit',minute:'2-digit'})}</h3><p>${names||'음식 기록'}</p><p><b>${Math.round(c)} kcal</b></p></div><button class="delete">×</button>`;el.querySelector('.delete').onclick=()=>{if(confirm('이 기록을 삭제할까요?')){state.meals=state.meals.filter(x=>x.id!==m.id);save()}};mealsEl.appendChild(el)})}
function addFood(f={}){let d=document.createElement('div');d.className='foodRow';d.innerHTML=`<div class="foodTop"><input class="name" placeholder="음식명" value="${f.name||''}"><input class="grams" type="number" placeholder="g" value="${f.grams||''}"></div><div class="nutrition"><input class="calories" type="number" placeholder="kcal" value="${f.calories||''}"><input class="carbs" type="number" placeholder="탄g" value="${f.carbs||''}"><input class="protein" type="number" placeholder="단g" value="${f.protein||''}"><input class="fat" type="number" placeholder="지g" value="${f.fat||''}"></div>`;$('#foods').appendChild(d)}
$('#addBtn').onclick=()=>{photoData='';$('#preview').hidden=true;$('#photoText').hidden=false;$('#photo').value='';$('#mealTime').value=localISO();$('#foods').innerHTML='';addFood();$('#memo').value='';$('#status').textContent='';$('#analyzeBtn').disabled=true;$('#mealDialog').showModal()};$('#cancelBtn').onclick=()=>$('#mealDialog').close();$('#addFood').onclick=()=>addFood();
$('#photo').onchange=async e=>{let f=e.target.files[0];if(!f)return;photoData=await resize(f,900,.72);$('#preview').src=photoData;$('#preview').hidden=false;$('#photoText').hidden=true;$('#analyzeBtn').disabled=false};
function resize(file,max,q){return new Promise(r=>{let im=new Image(),u=URL.createObjectURL(file);im.onload=()=>{let s=Math.min(1,max/Math.max(im.width,im.height)),c=document.createElement('canvas');c.width=im.width*s;c.height=im.height*s;c.getContext('2d').drawImage(im,0,0,c.width,c.height);URL.revokeObjectURL(u);r(c.toDataURL('image/jpeg',q))};im.src=u})}
$('#analyzeBtn').onclick=async()=>{let b=$('#analyzeBtn');b.disabled=true;$('#status').textContent='AI가 음식을 분석하고 있어요…';try{let res=await fetch('/api/analyze',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({image:photoData})}),data=await res.json();if(!res.ok)throw Error(data.error||'분석 실패');$('#foods').innerHTML='';(data.foods||[]).forEach(addFood);$('#status').textContent='AI 추정 결과예요. 양과 음식명을 확인한 뒤 저장하세요.'}catch(e){$('#status').textContent=e.message}finally{b.disabled=false}};
$('#mealForm').onsubmit=e=>{e.preventDefault();let foods=[...document.querySelectorAll('.foodRow')].map(d=>({name:d.querySelector('.name').value||'음식',grams:+d.querySelector('.grams').value||0,calories:+d.querySelector('.calories').value||0,carbs:+d.querySelector('.carbs').value||0,protein:+d.querySelector('.protein').value||0,fat:+d.querySelector('.fat').value||0}));state.meals.push({id:crypto.randomUUID(),type:$('#mealType').value,time:$('#mealTime').value,photo:photoData,foods,memo:$('#memo').value});save();$('#mealDialog').close()};
$('#settingsBtn').onclick=()=>{$('#goalInput').value=state.goal;$('#settingsDialog').showModal()};$('#settingsClose').onclick=()=>$('#settingsDialog').close();$('#saveSettings').onclick=()=>{state.goal=+$('#goalInput').value||1800;save();$('#settingsDialog').close()};
if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js');render();
