const num=v=>{const m=String(v??'').replace(/,/g,'').match(/-?\\d+(?:\\.\\d+)?/);const n=m?Number(m[0]):0;return Number.isFinite(n)?n:0};
const txt=v=>String(v??'').trim(), norm=s=>txt(s).toLowerCase().replace(/\\([^)]*\\)/g,'').replace(/[^0-9a-z가-힣]/g,'');
const pick=(o,...ks)=>{for(const k of ks)if(o?.[k]!=null&&txt(o[k]))return o[k];return ''};
const hasKorean=s=>/[가-힣]/.test(txt(s));
function amountUnit(v){const m=txt(v).match(/(\\d+(?:\\.\\d+)?)\\s*(ml|mL|㎖|g|kg|l)\\b/i);if(!m)return{amount:0,unit:''};let amount=+m[1],unit=m[2].toLowerCase();if(unit==='kg'){amount*=1000;unit='g'}if(unit==='l'){amount*=1000;unit='ml'}return{amount,unit:unit==='ml'?'mL':'g'}}
function packageAmount(quantity,name){
  const q=amountUnit(quantity);
  if(q.amount&&q.unit)return q;
  const fromName=amountUnit(name);
  if(fromName.amount&&fromName.unit)return fromName;
  return q;
}
function items(data){const r=data?.body?.items??data?.response?.body?.items??data?.items??[];return Array.isArray(r)?r:Array.isArray(r?.item)?r.item:r?.item?[r.item]:[]}
async function mfdsSearch(q,key){const u=new URL('https://apis.data.go.kr/1471000/FoodNtrCpntDbInfo03/getFoodNtrCpntDbInq03');[['serviceKey',key],['type','json'],['pageNo','1'],['numOfRows','30'],['FOOD_NM_KR',q]].forEach(x=>u.searchParams.set(...x));const r=await fetch(u,{headers:{Accept:'application/json'}});return r.ok?items(await r.json()):[]}
function mapMfds(o){const basis=txt(pick(o,'SERVING_SIZE','nutConSrtrQua','NUT_CONTSERVING')||'100g'),foodSize=txt(pick(o,'FOOD_SIZE','foodSize','SERVING_WT','FOOD_WEIGHT')),bi=amountUnit(basis),pi=amountUnit(foodSize);return{name:txt(pick(o,'FOOD_NM_KR','foodNmKr','foodNm','FOOD_NM')),maker:txt(pick(o,'MAKER_NM','companyNm','mkrNm','MFR_NM','CMPNY_NM','BSSH_NM')),reportNo:txt(pick(o,'ITEM_REPORT_NO','PRDLST_REPORT_NO')),basis,foodSize,nutritionBase:bi.amount||100,nutritionUnit:bi.unit||'g',productAmount:pi.amount||0,unit:pi.unit||bi.unit||'g',calories:num(pick(o,'AMT_NUM1','enerc','ENERC_KCAL')),protein:num(pick(o,'AMT_NUM3','prot','PROT_G')),fat:num(pick(o,'AMT_NUM4','fatce','FATCE_G')),carbs:num(pick(o,'AMT_NUM7','chocdf','CHOCDF_G')),source:'mfds'}}
function sim(a,b){a=norm(a);b=norm(b);if(!a||!b)return 0;if(a===b)return 1;if(a.includes(b)||b.includes(a))return .82;return 0}
function makerSim(a,b){a=norm(a);b=norm(b);if(!a||!b)return 0;return a===b?1:(a.includes(b)||b.includes(a))?.85:0}
function chooseOfficial(offName,offMaker,offQty,raw){const oq=amountUnit(offQty),ranked=raw.map(o=>{const m=mapMfds(o),name=sim(offName,m.name),maker=makerSim(offMaker,m.maker),mq=amountUnit(m.foodSize);let qty=0;if(oq.amount&&mq.amount&&oq.unit===mq.unit){const d=Math.abs(oq.amount-mq.amount)/Math.max(oq.amount,mq.amount);qty=d<=.01?1:d<=.1?.7:0}return{m,name,maker,qty,score:name*.72+maker*.18+qty*.10}}).sort((a,b)=>b.score-a.score),best=ranked[0],second=ranked[1];if(!best||best.name<.78)return null;if(norm(offMaker)&&norm(best.m.maker)&&best.maker===0&&best.name<.95)return null;if(second&&best.score-second.score<.035&&best.name<.95)return null;return{...best.m,matchScore:+best.score.toFixed(3),matchEvidence:{name:+best.name.toFixed(3),maker:+best.maker.toFixed(3),quantity:+best.qty.toFixed(3)}}}
export default async function handler(req,res){res.setHeader('Cache-Control','s-maxage=1800, stale-while-revalidate=43200');const code=txt(req.query?.code).replace(/\\D/g,'');if(code.length<8)return res.status(400).json({error:'INVALID_BARCODE'});try{const r=await fetch(`https://world.openfoodfacts.org/api/v2/product/${encodeURIComponent(code)}.json?fields=code,product_name,product_name_ko,generic_name_ko,brands,quantity,nutriments`,{headers:{'User-Agent':'MealLogAI/1.0'}}),d=await r.json();if(d.status!==1||!d.product)return res.status(404).json({found:false,code});const p=d.product,n=p.nutriments||{},offName=txt(p.product_name_ko||p.generic_name_ko||p.product_name),offMaker=txt(p.brands),offQty=txt(p.quantity),qi=packageAmount(offQty,offName),key=process.env.FOOD_API_KEY;let official=null;if(key){const all=[];for(const q of [p.product_name_ko,p.generic_name_ko,p.product_name].map(txt).filter(x=>hasKorean(x)&&x.length>=2))all.push(...await mfdsSearch(q,key));official=chooseOfficial(offName,offMaker,offQty,all)}const amount=qi.amount||official?.productAmount||100,unit=qi.unit||official?.unit||'g';if(official)return res.status(200).json({found:true,code,...official,barcodeName:offName,barcodeMaker:offMaker,quantity:offQty,productAmount:amount,displayAmount:amount,unit,source:'mfds+off',matchedOfficial:true,matchConfidence:'high'});const get=(...ks)=>{for(const k of ks){const z=Number(n[k]);if(Number.isFinite(z))return z}return 0},liquid=unit==='mL';return res.status(200).json({found:true,code,name:offName,maker:offMaker,barcodeName:offName,barcodeMaker:offMaker,quantity:offQty,productAmount:amount,displayAmount:amount,unit,nutritionBase:100,nutritionUnit:liquid?'mL':'g',basis:liquid?'100mL':'100g',calories:get('energy-kcal_100g','energy-kcal'),carbs:get('carbohydrates_100g','carbohydrates'),protein:get('proteins_100g','proteins'),fat:get('fat_100g','fat'),source:'off',matchedOfficial:false,matchConfidence:'unverified'})}catch(e){return res.status(500).json({error:'BARCODE_API_ERROR'})}}
